<a href="https://colab.research.google.com/github/wonyoung-ji/asiae_edu/blob/master/ML/200820_%ED%9A%8C%EA%B7%80_%EB%B6%84%EC%84%9D_%EB%B0%8F_K_%ED%8F%B4%EB%93%9C_%EA%B2%80%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 교차 검증
- 교차 검증의 의미
- 실습

### 방법 1. 홀드아웃
- 데이터: 훈련데이터와 테스트데이터
 + 훈련데이터: 훈련데이터(0.6) + 검증데이터(0.2) --> 테스트데이터 진행(0.2)

### 방법 2. K폴드 교차검증
- 데이터의 수가 적을 때 주로 사용
- Why? Default 연산량 * K개 만큼 해야 하므로 연산 속도가 너무 오래 걸림


- cross_val_score
- https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy import stats
from sklearn.datasets import load_boston

# https://scikit-learn.org/stable/datasets/index.html#boston-dataset

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
%matplotlib inline
boston = load_boston()

# pandas dataframe, 독립변수
bostonDF = pd.DataFrame(boston.data, columns=boston.feature_names)

# 종속변수
bostonDF['PRICE'] = boston.target
print('Size of Dataset:', bostonDF.shape)

Size of Dataset: (506, 14)


In [ ]:
bostonDF.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  PRICE
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 14 columns]

### 데이터 탐색
- 시각화, 통계 검정
 + 시각화는 각자 연습...!
- 변수 정의

https://scikit-learn.org/stable/datasets/index.html#boston-dataset

CRIM per capita crime rate by town

ZN proportion of residential land zoned for lots over 25,000 sq.ft.

INDUS proportion of non-retail business acres per town

CHAS Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)

NOX nitric oxides concentration (parts per 10 million)

RM average number of rooms per dwelling

AGE proportion of owner-occupied units built prior to 1940

DIS weighted distances to five Boston employment centres

RAD index of accessibility to radial highways

TAX full-value property-tax rate per $10,000

PTRATIO pupil-teacher ratio by town

B 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town

LSTAT % lower status of the population

MEDV Median value of owner-occupied homes in $1000’s

## 머신러닝 모형 만들기

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# 독립변수, 종속변수 분리
y_target = bostonDF['PRICE']
X_data = bostonDF.drop(['PRICE'], axis = 1, inplace = False)    # 독립변수 데이터만 넣기 위해 종속변수인 Price를 빼버림

# 훈련데이터, 테스트데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X_data, y_target, test_size = 0.3, random_state = 1)

# 모형 만들기 (선형회귀)
lr_model = LinearRegression()

# 모형 학습시키기
lr_model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
# 예측
y_preds = lr_model.predict(X_test)
y_preds # 해당 결과 값은 예측된 가격을 의미함

array([32.3914647 , 27.94401279, 17.83762764, 21.66941388, 18.93639614,
       20.01995795, 32.63414961, 17.86179976, 24.73211676, 26.77346826,
       27.26138023, 28.63243014, 21.16103038, 27.15098589, 23.33198614,
       21.02894005, 17.11819755, 37.52455938, 30.69864427,  8.46104486,
       20.83966032, 16.26732451, 25.05030307, 24.8069032 , 31.6789299 ,
       10.98989363, 13.54111562, 16.54697099, 35.86699683, 14.69589266,
       21.05655107, 13.90301353, 43.01321262, 17.80335305, 21.68817023,
       20.45077825, 17.38095983, 26.81334904, 10.08706217, 19.96174586,
       24.1983249 , 21.00202622, 29.38682967, 16.33215467, 19.37439646,
       14.45525235, 39.52670798, 18.18535021, 26.38536303, 20.41420863,
       25.08511581, 24.40208165, 24.87902769, 26.97887956,  4.93921657,
       24.0001365 , 10.66711602, 26.98494775, 16.63507993, 35.31652989,
       19.49249915, 27.37577863, 16.53965715, 19.09746715, 11.06765336,
       32.03445261, 36.15847648, 21.53547868, 24.96434626, 25.50

- mean_squared_error(MSE): **실제값과 예측값의 차이**를 제곱 후 평균한 것
- RMSE: 실제 오류 평균보다 더 커지는 특성이 있어서 루트를 씌운 것

In [ ]:
mse = mean_squared_error(y_test, y_preds)
print(mse)

19.831323672062922


In [ ]:
rmse = np.sqrt(mse)
print(rmse)

4.4532374371981245


## K 폴드 적용
- cross_val_score() 함수를 활용하여 RMSE 평균값 구해보기
+ 5개 폴드값

In [ ]:
from sklearn.model_selection import cross_val_score

neg_mse_scores = cross_val_score(lr_model, X_data, y_target, scoring="neg_mean_squared_error", cv=5)
print(neg_mse_scores) # 반환값이 음수로 나오는 것은 무시,,,

[-12.46030057 -26.04862111 -33.07413798 -80.76237112 -33.31360656]


In [ ]:
# neg_mse_scores를 양수로 변환시킨 뒤, 루트 씌우기

rmse_scores = np.sqrt(-1 * neg_mse_scores)
print(rmse_scores)

[3.52991509 5.10378498 5.75101191 8.9867887  5.77179405]


In [ ]:
np.mean(rmse_scores)   # RMSE (예측-실제)의 오차값을 가장 작은 수로 만들기 위해 독립변수를 조작. 여러번 돌려봐야 함

5.828658946215802

- 위의 RMSE 크기를 줄이기 위해서는?(좋은 모형을 만들기 위해서는?) 
 + 기존의 13개 변수(price는 종속 변수였으니깐 제외 ㅎㅎ) 중에서 의미 있는 변수만 선택하여 계속해서 돌려봐야 함...!