<a href="https://colab.research.google.com/github/wonyoung-ji/NLP/blob/master/3%EC%9D%BC%EC%B0%A8/%EB%8B%A8%EC%96%B4%EC%9D%98%ED%91%9C%ED%98%84_%EC%8B%A4%EC%8A%B5_OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## OneHotEncoding

In [ ]:
word_ls = ['원숭이','바나나','사과','코끼리']

In [ ]:
from collections import defaultdict
import numpy as np

In [ ]:
# {단어 : 인덱스} 사전 구축
word2id_dic = defaultdict(lambda:len(word2id_dic))

for word in word_ls:
  word2id_dic[word]

defaultdict(<function __main__.<lambda>>,
            {'바나나': 1, '사과': 2, '원숭이': 0, '코끼리': 3})

In [ ]:
# 고유단어갯수 : 4개
n_unique_words = len(word2id_dic)
n_unique_words 

4

In [ ]:
# 원핫 벡터를 만들기 위해 비어있는 벡터 생성
one_hot_vectors = np.zeros((len(word_ls), n_unique_words))
one_hot_vectors

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 단어고유 인덱스
for i, word in enumerate(word_ls):
  index = word2id_dic[word]
  one_hot_vectors[i, index] += 1
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Sklearn을 활용한 one-hot encoding

In [ ]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# 예제 데이터 배열
values = array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [ ]:
# 문자열에 숫자 할당
label_enc = LabelEncoder()      # 선언
int_enc = label_enc.fit_transform(values)
int_enc

array([2, 0, 1, 3])

In [ ]:
#binary encode
onehot_enc = OneHotEncoder(sparse=False)    # 선언. True: 행렬 / False: 배열
int_enc = int_enc.reshape(len(int_enc),1)   # 가로에서 세로로 변경
print(int_enc)
onehot_enc = onehot_enc.fit_transform(int_enc)
print(onehot_enc)

[[2]
 [0]
 [1]
 [3]]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
