<a href="https://colab.research.google.com/github/wonyoung-ji/NLP/blob/master/4%EC%9D%BC%EC%B0%A8/%EB%8B%A8%EC%96%B4%EC%9D%98%ED%91%9C%ED%98%84_%EC%8B%A4%EC%8A%B5_BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Bag of Words 실습

In [ ]:
import numpy as np

## defaultdict를 활용한 BOW

### 실습예제 01

In [ ]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
        '오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [ ]:
doc_ls=[]
for doc in docs:
  doc_ls.append(doc.split(' '))      # 띄어쓰기로 토큰화
doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [ ]:
from collections import defaultdict
word2id = defaultdict (lambda : len(word2id))
word2id

defaultdict(<function __main__.<lambda>>, {})

In [ ]:
for doc in doc_ls:
  for token in doc:
    word2id[token]
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '먹이를': 6,
             '보고': 4,
             '사과를': 8,
             '오늘': 0,
             '원숭이를': 3,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리': 2})

In [ ]:
# # 내가 한 방법
# one_hot_vectors = np.zeros((len(doc_ls), len(word2id)),dtype=int)

# for i, doc in enumerate(doc_ls):
#   for token in doc:
#    for words in word2id.keys():
#       if token == words:
#         index = word2id[words]
#         one_hot_vectors[i, index] += 1
# one_hot_vectors

array([[1, 1, 2, 1, 1, 1, 1, 1, 0],
       [1, 1, 0, 0, 0, 1, 0, 1, 1]])

In [ ]:
# 다른 방법
BoW_ls=[]
for i, doc in enumerate(doc_ls):
  bow = np.zeros(len(word2id),dtype=int)
  for token in doc:
    bow[word2id[token]] += 1
  BoW_ls.append(bow.tolist())
BoW_ls

[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [ ]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value,key) for key, value in word2id.items())
print('sorted_vocab', sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [ ]:
vocab = []
for v in sorted_vocab:
  vocab.append(v[1])
vocab

['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']

In [ ]:
for i in range(len(docs)):
  print("문서{} : {}".format(i, docs[i]))
  ICD.display(pd.DataFrame([BoW_ls[i]],columns=vocab))
  print("\n\n")

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1 : 오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

### 실습예제 02: 단어의 순서를 고려하지 않은 BOW

In [ ]:
docs = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
        '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [ ]:
doc_ls = []
for doc in docs:
  doc_ls.append(doc.split(' '))
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [ ]:
from collections import defaultdict
word2id = defaultdict(lambda: len(word2id))

In [ ]:
for doc in doc_ls:
  for token in doc:
    word2id[token]
word2id

defaultdict(<function __main__.<lambda>>,
            {'나는': 0,
             '싫어해': 6,
             '양념': 1,
             '좋아해': 3,
             '치킨을': 2,
             '하지만': 4,
             '후라이드': 5})

In [ ]:
BoW_ls = []
for i, doc in enumerate(doc_ls):
  bow = np.zeros(len(word2id),dtype=int)
  for token in doc:
    bow[word2id[token]] += 1
  BoW_ls.append(bow.tolist())

BoW_ls

[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [ ]:
sorted_vocab = sorted((values,key) for key, values in word2id.items())
print(sorted_vocab)

[(0, '나는'), (1, '양념'), (2, '치킨을'), (3, '좋아해'), (4, '하지만'), (5, '후라이드'), (6, '싫어해')]


In [ ]:
vocab = []
for v in sorted_vocab:
  vocab.append(v[1])
vocab

['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']

In [ ]:
for i in range(len(docs)):
  print('문서{}: {}'.format(i,docs[i]))
  ICD.display(pd.DataFrame([BoW_ls[i]],columns=vocab))
  print('\n\n')

문서0: 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1




문서1: 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1

## sklearn 활용한 BOW

In [ ]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
        '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [ ]:
# 토큰빈도계산 : CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
#선언
count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs)
print(BoW.toarray())
vocab = count_vect.get_feature_names()
print(vocab)

[[1 1 1 0 1 1 1 1 2]
 [2 1 1 1 2 1 2 2 2]]
['동물원에서', '먹이를', '보고', '사과를', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리']


In [ ]:
for i in range(len(docs)):
  print('문서{} : {}'.format(i,docs[i]))
  ICD.display(pd.DataFrame([BoW.toarray()[i]],columns=vocab))
  print('\n\n')

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2




문서1 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      2    1   1    1   2     1      2   2    2

## gensim 활용한 BOW

In [ ]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
        '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [ ]:
from gensim import corpora

doc_ls = []
for doc in docs:
  doc_ls.append(doc.split(' '))
print(doc_ls)
print('--------')


id2word = corpora.Dictionary(doc_ls)
print(id2word)

BoW = []
for doc in doc_ls:
  BoW.append(id2word.doc2bow(doc))

BoW

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'], ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어', '오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]
--------
Dictionary(9 unique tokens: ['동물원에서', '먹이를', '보고', '오늘', '원숭이를']...)


[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)],
 [(0, 2), (1, 1), (2, 1), (3, 2), (4, 1), (5, 2), (6, 2), (7, 2), (8, 1)]]

In [ ]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD
import pandas as pd

vocab = [id2word[i] for i in id2word.keys()]

for i in range(len(docs)):
  print('문서{} : {}'.format(i,docs[i]))
  ICD.display(pd.DataFrame([sparse2full(BoW[i],len(vocab))],columns=vocab))
  print('\n\n')

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    1.0  1.0  1.0  1.0   1.0    1.0  1.0  2.0  0.0




문서1 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    2.0  1.0  1.0  2.0   1.0    2.0  2.0  2.0  1.0