<a href="https://colab.research.google.com/github/wonyoung-ji/NLP/blob/master/4%EC%9D%BC%EC%B0%A8/%EB%8B%A8%EC%96%B4%EC%9D%98%ED%91%9C%ED%98%84_%EC%8B%A4%EC%8A%B53_TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 직접 TF-IDF 구현

## DTM구하기

In [186]:
docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [187]:
doc_ls=[]
for doc in docs:
  doc_ls.append(doc.split(' '))
doc_ls

[['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [188]:
from collections import defaultdict
word2id = defaultdict(lambda: len(word2id))

for doc in doc_ls:
  for token in doc:
    word2id[token]
  
print(word2id)

defaultdict(<function <lambda> at 0x7f05082177b8>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4, '원숭이에게': 5, '바나나를': 6, '줬어': 7})


In [189]:
import numpy as np

DTM = np.zeros((len(doc_ls),len(word2id)),dtype=int)
for i, doc in enumerate(doc_ls):
  for token in doc:
    DTM[i,word2id[token]] += 1
DTM

array([[1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 2, 1]])

## TF 구하기

In [243]:
TF = np.zeros((len(doc_ls),len(word2id)))

for i, doc in enumerate(doc_ls):
  for token in doc:
    TF[i,word2id[token]] += 1
  TF[i] = TF[i]/len(doc_ls[i])
TF

array([[0.2, 0.2, 0.2, 0.2, 0.2, 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. , 0.2, 0.4, 0.2]])

## IDF 구하기
- idf = log(총문서수 / 단어가 등장한 문서수)

In [244]:
#총 문서수
print(len(doc_ls))

# 단어가 등장한 문서수
count_doc = np.zeros(len(word2id))
for i in range(len(word2id)):
  count_doc[i] = np.count_nonzero(DTM[:,i])
print(count_doc)

2
[1. 2. 1. 1. 1. 1. 1. 1.]


In [256]:
#idf 구하기 = log(총문서수 / 단어가 등장한 문서수)
import math

IDF = np.zeros(len(word2id))

for i in range(len(word2id)):
  IDF[i] = math.log10(len(doc_ls)/count_doc[i])
IDF

array([0.30103, 0.     , 0.30103, 0.30103, 0.30103, 0.30103, 0.30103,
       0.30103])

## TF-IDF 구하기

In [261]:
TF_IDF = np.zeros((len(doc_ls),len(word2id)))

for i in range(len(doc_ls)):
  TF_IDF[i] = TF[i] * IDF[t]

print(TF_IDF)

[[0.060206 0.060206 0.060206 0.060206 0.060206 0.       0.       0.      ]
 [0.       0.060206 0.       0.       0.       0.060206 0.120412 0.060206]]


## 데이터프레임

In [270]:
import pandas as pd

sorted_vocab = sorted((values,keys) for keys, values in word2id.items())
vocab = [v[1] for v in sorted_vocab]

DF = pd.DataFrame(TF_IDF, columns = vocab)
DF

오늘     동물원에서      원숭이와  ...     원숭이에게      바나나를        줬어
0  0.060206  0.060206  0.060206  ...  0.000000  0.000000  0.000000
1  0.000000  0.060206  0.000000  ...  0.060206  0.120412  0.060206

[2 rows x 8 columns]