In [ ]:
d={'height':180,'weight':78,'temperature':36,'eyesight':1}
a=list(d.values())
b=list(d.keys())
for i in range(len(d)):
    if a[i]==78:
        print(b[i])
    
    

In [ ]:
d={'height':180,'weight':78,'temperature':36,'eyesight':1}
a=d.items()
print(a)
print('*'*70)

for i in d.items():
    if i[1]==78:
        print(i[0])
        break


In [ ]:
d={'height':180,'weight':78,'temperature':36,'eyesight':1}
a=d.items()
print(a)
a(1)

In [ ]:
for i in d.items():
    if i[1]==78:
        print(i[0])

In [ ]:
def sum_n(n):
    sum=0
    for i in range(1,n+1):
        sum=sum+i
    return sum

sum_n(4)



In [83]:
d={'height':180,'weight':78,'temperature':36,'eyesight':1}

for i in d.items():
    if i[1]==78:
        print(i[0])
        break

weight


In [84]:
d={'height':180,'weight':78,'temperature':36,'eyesight':1}

for i in d.items():
    print(i)


('height', 180)
('weight', 78)
('temperature', 36)
('eyesight', 1)


In [14]:
d={'1반':[60,80,30],'2반':[78,54,98],'3반':[100,50,70],'4반':[70,60,80]}
print(d.items())
print()
print()
print()
for i in d.items():
    print(i[1])

dict_items([('1반', [60, 80, 30]), ('2반', [78, 54, 98]), ('3반', [100, 50, 70]), ('4반', [70, 60, 80])])



[60, 80, 30]
[78, 54, 98]
[100, 50, 70]
[70, 60, 80]


In [54]:
#1부터 10,000까지 8이 몇번 등장?
seq=list(range(1,100+1))
seq1=str(seq)
seq1.count('8')

20

In [55]:
seq=list(range(1,100+1))
a=0
for i in str(seq):
    if i == '8':
        a=a+1
print(a)

20


In [56]:
seq1

'[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]'

In [60]:
name=['홍길동','이성순신','이성계']
name1=str(name)
a=0
for i in name1:
    if i == '신':
        a=a+1
print(a)
    

1


In [64]:
''.join(name)

'홍길동이성순신이성계'

In [71]:
from pandas import Series, DataFrame
import pandas as pd

a={'country':['벨기에','인도','브라질'],
   'capital':['브뤼셀','뉴델리','브라질리아'],
   'population':['1천만명','13억명','2억명']}
b=DataFrame(a)


SyntaxError: cannot assign to function call (<ipython-input-71-6f71df55c1bd>, line 8)

In [82]:
from pandas import Series, DataFrame
import pandas as pd
a={'country':['벨기에','인도','브라질'],
   'capital':['브뤼셀','뉴델리','브라질리아'],
   'population':['1천만명','13억명','2억명']}

b=DataFrame(a)
b.loc[1,'population']='14억명'
b


country capital population
0     벨기에     브뤼셀       1천만명
1      인도     뉴델리       14억명
2     브라질   브라질리아        2억명

In [85]:
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [86]:
arr

array([1, 2, 3, 4])

In [91]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [92]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
arr=np.array([[1,2,3],['a',5,6]])
arr.shape

(2, 3)

In [99]:
arr.ndim

2

In [100]:
arr.dtype

dtype('<U11')

In [115]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [116]:
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [117]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [118]:
np.multiply(arr1,arr2)

array([[ 5, 12],
       [21, 32]])

In [109]:
np.dot(arr1,arr2)

array([[19, 22, 25],
       [43, 50, 57]])

In [126]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr_1=arr[0:2,1:3]
arr_1

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

In [127]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0,2]

3

In [128]:
arr[[0,1,2,],[2,0,1]]

array([3, 4, 8])

In [133]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
inx= arr>3
print(inx)

print(arr[inx])  #조건을 변수에 저장해놓고 배열[조건저장한 변수]-->조건에 맞는 행 추출


[[1 2 3]
 [4 5 6]]
[[False False False]
 [ True  True  True]]
[4 5 6]


In [134]:
redwine=np.loadtxt(fname='C:\wonyoung\winequality-red.csv',delimiter=';',skiprows=1) #skiprows=column명 제외하고 숫자값만 가져오겠다
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [135]:
redwine.shape

(1599, 12)

In [138]:
redwine.ndim

2

In [139]:
redwine.sum()

152084.78194

In [140]:
redwine.mean()

7.926036165311652

In [141]:
redwine.mean(axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

In [143]:
redwine[:,].mean()

7.926036165311652

In [144]:
redwine.max(axis=0)

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [145]:
redwine.min(axis=1)

array([0.   , 0.   , 0.04 , ..., 0.076, 0.075, 0.067])

In [148]:
d={'height':180,'weight':78,'temperature':36,'eyesight':1}
for i in d.items():
    if i[1]==78:
        print(i[0])
        

weight


In [149]:
import numpy as np


In [159]:
import numpy as np

arr=np.arange(15)
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [164]:
arr.reshape(-1,3) #-1:열에 맞게 행의 갯수를 정해라

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [178]:
arr.reshape(2,3,4,5) 

ValueError: cannot reshape array of size 15 into shape (2,3,4,5)

In [179]:
a= np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [193]:
import numpy as np
a= np.arange(24)
b=a.reshape(2,3,4)  #차원 2개로 나눠서 3x4
c=a.reshape(3,4,2)
print(c)
print(c.ndim) #3,4,2로 이루어진 3차원

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
3


In [200]:

arr=np.arange(15)
b=arr.reshape(5,1,3)
b.ndim

3

In [201]:
a=np.array([4,5,6])
a

array([4, 5, 6])

In [205]:
b=np.zeros([3,5])

In [206]:
c=np.array([[1,2,3],[2,3,4]])
c

array([[1, 2, 3],
       [2, 3, 4]])

In [207]:
c=np.array([(1,5,2),(2.4,5,6)])
c

array([[1. , 5. , 2. ],
       [2.4, 5. , 6. ]])

In [210]:
np.ones_like([[2,3,4],[6,23,2]])

array([[1, 1, 1],
       [1, 1, 1]])

In [211]:
np.arange(5,10,2) #5에서 9까지 2씩

array([5, 7, 9])

In [213]:
arr=np.linspace(0,2,9)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [215]:


x=np.linspace(0,2*np.pi,100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [216]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [224]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [226]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
c

array([20, 29, 38, 47])

In [227]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [232]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
c
ind=a<35
ind
a[ind]

array([20, 30])

In [284]:
rg=np.random.default_rng(2) #난함수 발생시킴..?

a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.26161213 0.29849114 0.81422574]
 [0.09191594 0.60010053 0.72856053]]


In [242]:
np.random.seed(2)
c=np.random.rand(2,3) # 0부터 1사이 균일 분포의 난수 생성
c

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482]])

In [245]:
array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482]])

NameError: name 'array' is not defined

In [252]:
rg=np.random.default_rng(1) #난함수 발생시킴..?

a = np.ones((2,3), dtype=int)
b = rg.random((2,3))

b+=a;b   #그냥 +는 다른 곳에 저장X. (실수)+=(정수)할 때는 저장 O


array([[1.51182162, 1.9504637 , 1.14415961],
       [1.94864945, 1.31183145, 1.42332645]])

In [255]:
a = rg.random((2,3))
a

array([[0.20345524, 0.26231334, 0.75036467],
       [0.28040876, 0.48519097, 0.9807372 ]])

In [256]:
a.sum()

2.962470185966965

In [257]:
a.max()

0.9807371998012386

In [258]:
a.min()

0.20345524067614962

In [285]:
b = np.arange(24).reshape(4,3,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [286]:
b.sum(axis=0)


array([[36, 40],
       [44, 48],
       [52, 56]])

In [287]:
b.sum(axis=1)

array([[ 6,  9],
       [24, 27],
       [42, 45],
       [60, 63]])

In [288]:
b.sum(axis=2)

array([[ 1,  5,  9],
       [13, 17, 21],
       [25, 29, 33],
       [37, 41, 45]])

In [289]:
b.sum(axis=3)

AxisError: axis 3 is out of bounds for array of dimension 3

In [290]:
a=np.arange(6).reshape(2,3)+10
a


array([[10, 11, 12],
       [13, 14, 15]])

In [291]:
np.argmax(a) --># 5번째가 가장 큰 값이다고 알려줌

SyntaxError: invalid syntax (<ipython-input-291-7fb456b683d9>, line 1)

In [276]:
np.argmax(a,axis=0)

array([1, 1, 1], dtype=int64)

In [278]:
a = np.arange(10)**3
#array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
a[:6:2] = 1000;a #0에서부터 5번째까지 가는데 2씩 1000을 넣어주세요

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [279]:
a[ : :-1]  #a의 리버스

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [338]:
def f(x,y):
    print('x=',x)
    print('y=', y)
    return 10*x + y

b=np.fromfunction(f,(1,6),dtype=int)
b

x= [[0 0 0 0 0 0]]
y= [[0 1 2 3 4 5]]


array([[0, 1, 2, 3, 4, 5]])

In [294]:
b[2,3]

23

In [296]:
b[2:4,1:3]

array([[21, 22],
       [31, 32]])

In [303]:
a=np.floor(10*rg.random((3,4)))
a

array([[6., 4., 5., 5.],
       [8., 4., 8., 6.],
       [8., 4., 6., 3.]])

array([6., 4., 5., 5., 8., 4., 8., 6., 8., 4., 6., 3.])

In [317]:
a=np.floor(10*rg.random((3,4)))
a
a.ravel()
a.reshape(2,6)
a.shape

(3, 4)

In [318]:
a.T.shape

(4, 3)

In [319]:
a = np.floor(10*rg.random((2,2)))
>>> a

array([[9., 6.],
       [0., 2.]])

In [320]:
b = np.floor(10*rg.random((2,2)))
>>> b

array([[6., 3.],
       [4., 8.]])

In [322]:
np.vstack((a,b))

array([[9., 6.],
       [0., 2.],
       [6., 3.],
       [4., 8.]])

In [323]:
np.hstack((a,b))

array([[9., 6., 6., 3.],
       [0., 2., 4., 8.]])

In [325]:
a = np.floor(10*rg.random((2,12)))
>>> a

array([[9., 2., 6., 3., 6., 0., 4., 5., 6., 6., 8., 2.],
       [1., 3., 5., 9., 7., 7., 9., 2., 2., 4., 2., 6.]])

In [326]:
np.hsplit(a,3)

[array([[9., 2., 6., 3.],
        [1., 3., 5., 9.]]),
 array([[6., 0., 4., 5.],
        [7., 7., 9., 2.]]),
 array([[6., 6., 8., 2.],
        [2., 4., 2., 6.]])]

In [327]:
a = np.array([[ 0,  1,  2,  3],
...               [ 4,  5,  6,  7],
...               [ 8,  9, 10, 11]])

In [328]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [332]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])