In [1]:
import numpy as np
a=np.array([[15,20,25,30],[35,40,45,50]])
a


array([[15, 20, 25, 30],
       [35, 40, 45, 50]])

In [10]:
b=np.arange(15,51,5)
b.reshape(2,4)


array([[15, 20, 25, 30],
       [35, 40, 45, 50]])

In [54]:
m=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
print(m[1,2])
print(m[2,4])
print(m[1,1:3])
print(m[1:3,2])
print(m[0:2,3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]
